version: '3'
services:
  # flyway:
    #image: flyway/flyway
      # command: -url=jdbc:mysql://db -schemas=myschema -user=root -password=P@ssw0rd -connectRetries=60 migrate
      #volumes:
      #  - .:/flyway/sql
        # depends_on:
      #      - db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=MovieRegistry
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data


